[global]
monitor = 0

width = 300
height = 300
origin = top-right
offset = 15x15

notification_limit = 20

progress_bar = true
progress_bar_height = 10
progress_bar_frame_width = 1
progress_bar_min_width = 150
progress_bar_max_width = 300
progress_bar_corner_radius = 3

icon_corner_radius = 5

indicate_hidden = yes

separator_height = 1
padding = 8
horizontal_padding = 8
text_icon_padding = 0
frame_width = 2

gap_size = 0
separator_color = frame

sort = yes

font = FantasqueSansM Nerd Font 12
line_height = 0
markup = full
format = "<b>%s</b>\n%b"
alignment = left
vertical_alignment = center
show_age_threshold = 60
ellipsize = middle
ignore_newline = no
stack_duplicates = true
hide_duplicate_count = false
show_indicators = yes

enable_recursive_icon_lookup = true
icon_theme = "Tela-blue-dark, Adwaita"
icon_position = left
min_icon_size = 32
max_icon_size = 128

sticky_history = yes
history_length = 20

browser = /usr/bin/xdg-open
always_run_script = true
title = Dunst
class = Dunst
corner_radius = 5

ignore_dbusclose = false

layer = top
force_xwayland = false

force_xinerama = false

mouse_left_click = close_current
mouse_middle_click = do_action, close_current
mouse_right_click = close_all

[experimental]
per_monitor_dpi = false

[urgency_low]
timeout = 10

[urgency_normal]
timeout = 10

[urgency_critical]
timeout = 0
