# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/23b6049f-1200-485f-8098-c88da263fbf2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos" = {
    device = "/dev/disk/by-uuid/be51545c-3626-44eb-a8ca-ca65d770667e";
  };

  environment.etc."crypttab".text = ''
    home /dev/disk/by-uuid/be31b55a-ca09-4531-b880-5886ac8d3793 /root/home.key
  '';

  fileSystems."/home" = { 
    device = "/dev/mapper/home";
    fsType = "ext4";
  };

  # boot.initrd.luks.devices."home" = {
  #   device = "/dev/disk/by-uuid/be31b55a-ca09-4531-b880-5886ac8d3793";
  #   preLVM = false;
  #   keyFile = "/root/home.key";
  # };

  fileSystems."/boot" = { 
    device = "/dev/disk/by-uuid/D638-9DAD";
    fsType = "vfat";
  };

  boot.initrd.luks.devices."swap" = {
    device = "/dev/disk/by-uuid/7a8cc0eb-6e8e-4b64-886f-5b9e27f39a0a";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9f45bb92-cb52-4018-907d-f32c976659ea"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
